package com.spannering.spanneringapp;

import com.spannering.data.SpannerRunner;
import com.spannering.model.Door;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
public class DoorsController {


    /**
     * This should return a list of all doors
     */
    @CrossOrigin(origins = "http://localhost:3000")
    @RequestMapping(value = "/api/getAllDoors", method = RequestMethod.GET)
    public List<Door> getAllDoors() {

        System.out.println("getAllDoors()");
        return (List<Door>) SpannerRunner.run(SpannerRunner.GET_ALL_DOORS);
    }


    /**
     * - Pass in a door object and add it to the database
     * - The door_id should be autogenerated. For our autogenerated keys, we use UUID
     */
    @CrossOrigin(origins = "http://localhost:3000")
    @RequestMapping(value = "/api/addDoor", method = RequestMethod.POST)
    public Door add(@RequestBody String doorName) {

        System.out.println("add(" + doorName + ")");
        final Door newDoor = new Door(UUID.randomUUID().hashCode(), doorName); //TODO: encapsulate door id creation
        return (Door) SpannerRunner.run(SpannerRunner.createAddDoor(newDoor));

    }


    /**
     * - Pass in a door object and add it to the database
     * - The door_id should be autogenerated. For our autogenerated keys, we use UUID
     */
    @CrossOrigin(origins = "http://localhost:3000")
    @RequestMapping(value = "/api/deleteAllDoors", method = RequestMethod.DELETE)
    public void deleteAllDoors() {

        System.out.println("deleteAllDoors()");
        SpannerRunner.run(SpannerRunner.DELETE_ALL_DOORS);

    }

}
